// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"gmd4uh25pe","name":"itemsCRUD","description":"","endpoint":"https://gmd4uh25pe.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]},{"id":"f9e98iubld","name":"sampleCloudApi","description":"","endpoint":"https://f9e98iubld.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]},{"id":"8np5mxfnn3","name":"shopCRUD","description":"","endpoint":"https://8np5mxfnn3.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/shop","/shop/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:196ddb14-58c6-4509-b5a4-806186bb02be',
    'aws_cognito_region': 'us-east-1',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"providence-mobilehub-52139375-items","attributes":[{"name":"ID","type":"S"},{"name":"itemDescription","type":"S"},{"name":"itemName","type":"S"},{"name":"itemPrice","type":"N"}],"indexes":[],"region":"us-east-1","hashKey":"ID"},{"tableName":"providence-mobilehub-52139375-shop","attributes":[{"name":"ID","type":"S"},{"name":"itemDescription","type":"S"},{"name":"itemName","type":"S"},{"name":"itemPrice","type":"N"}],"indexes":[],"region":"us-east-1","hashKey":"ID"}],
    'aws_project_id': 'd75cc04f-ac5a-4678-b419-33147ecbf9e6',
    'aws_project_name': 'providence',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'providence-deployments-mobilehub-52139375',
    'aws_resource_name_prefix': 'providence-mobilehub-52139375',
}

export default awsmobile;
